define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "HeaderTitleFieldLabel": "Header title",
    "HeaderSubtitleFieldLabel": "Header subtitle",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ListFieldLabel": "Suggestions list",
    "VoteListFieldLabel": "Votes list",
    "CommentListFieldLabel": "Comments list",
    "CategoryListFieldLabel": "Category list",
    "CategoryListDefaultOptionLabel": "Use default categories",
    "SubcategoryListFieldLabel": "Subcategory list",
    "SubcategoryListNoneOptionLabel": "Do not use subcategories",
    "CreateSuggestionsListButtonLabel": "Create or update suggestions list",
    "CreateVotesListButtonLabel": "Create or update votes list",
    "CreateCommentsListButtonLabel": "Create or update comments list",
    "CreateCategoryListButtonLabel": "Create or update category list",
    "CreateSubcategoryListButtonLabel": "Create or update subcategory list",
    "CreateSuggestionsListProgressMessage": "Creating or updating the suggestions list...",
    "CreateVotesListProgressMessage": "Creating or updating the votes list...",
    "CreateCommentsListProgressMessage": "Creating or updating the comments list...",
    "CreateCategoryListProgressMessage": "Creating or updating the category list...",
    "CreateSubcategoryListProgressMessage": "Creating or updating the subcategory list...",
    "CategoryManagementLabel": "Manage categories",
    "SubcategoryManagementLabel": "Manage subcategories",
    "CategoryItemsFieldLabel": "Existing categories",
    "SubcategoryItemsFieldLabel": "Existing subcategories",
    "CategoryDropdownPlaceholder": "No categories found",
    "SubcategoryDropdownPlaceholder": "No subcategories found",
    "NewCategoryFieldLabel": "New category name",
    "NewSubcategoryFieldLabel": "New subcategory name",
    "NewCategoryFieldPlaceholder": "Enter a category name",
    "NewSubcategoryFieldPlaceholder": "Enter a subcategory name",
    "AddCategoryButtonAriaLabel": "Add category",
    "AddSubcategoryButtonAriaLabel": "Add subcategory",
    "RemoveCategoryButtonAriaLabel": "Remove selected category",
    "RemoveSubcategoryButtonAriaLabel": "Remove selected subcategory",
    "CategoryNameMissingMessage": "Enter a name before adding a category.",
    "SubcategoryNameMissingMessage": "Enter a name before adding a subcategory.",
    "CategoryListNotConfiguredMessage": "Select or create a category list or use the default categories before managing entries.",
    "SubcategoryListNotConfiguredMessage": "Select or create a subcategory list before managing entries.",
    "CategoryUpdateProgressMessage": "Updating categories...",
    "SubcategoryUpdateProgressMessage": "Updating subcategories...",
    "CategoryUpdateSuccessMessage": "Categories updated.",
    "SubcategoryUpdateSuccessMessage": "Subcategories updated.",
    "CategoryUpdateErrorMessage": "We couldn't update the category list. Please try again.",
    "SubcategoryUpdateErrorMessage": "We couldn't update the subcategory list. Please try again.",
    "CategoryLoadErrorMessage": "We couldn't load categories. Please verify the list and try again.",
    "SubcategoryLoadErrorMessage": "We couldn't load subcategories. Please verify the list and try again.",
    "CategoryAddedMessage": "Added category \"{0}\".",
    "SubcategoryAddedMessage": "Added subcategory \"{0}\".",
    "CategoryRemovedMessage": "Removed the selected category.",
    "SubcategoryRemovedMessage": "Removed the selected subcategory.",
    "CategorySelectionMissingMessage": "Select a category before removing it.",
    "SubcategorySelectionMissingMessage": "Select a subcategory before removing it.",
    "CreateListSuccessMessage": "The list \"{0}\" is ready to use.",
    "CreateListAlreadyExistsMessage": "The list already existed. Missing fields were added if necessary.",
    "CreateListNameMissingMessage": "Enter a name before creating the list.",
    "CreateListErrorMessage": "We couldn't create or update the list. Please try again.",
    "CreateListPromptMessage": "Enter a name for the {0}:",
    "CreateListPromptSuggestionsLabel": "suggestions list",
    "CreateListPromptVotesLabel": "votes list",
    "CreateListPromptCommentsLabel": "comments list",
    "CreateListPromptCategoryLabel": "category list",
    "CreateListPromptSubcategoryLabel": "subcategory list",
    "UseTableLayoutToggleLabel": "Suggestion layout",
    "UseTableLayoutToggleOnText": "Table",
    "UseTableLayoutToggleOffText": "Cards",
    "AddSuggestionSectionTitle": "Add a suggestion",
    "HideSectionLabel": "Hide section",
    "ShowSectionLabel": "Show section",
    "PreviousButtonText": "Previous",
    "NextButtonText": "Next",
    "PaginationPageLabel": "Page {0}",
    "CreatedLabel": "Created",
    "LastModifiedLabel": "Last modified",
    "CompletedLabel": "Completed",
    "VotesRemainingLabel": "Votes remaining",
    "CategoryLabel": "Category",
    "SubcategoryLabel": "Subcategory",
    "SubmitSuggestionButtonText": "Submit suggestion",
    "VoteButtonText": "Vote",
    "VotesClosedText": "Votes closed",
    "MarkAsDoneButtonText": "Mark as done",
    "CommentsLabel": "Comments",
    "AddCommentButtonText": "Add comment",
    "VoteSingularLabel": "vote",
    "VotesLabel": "Votes",
    "SimilarSuggestionsTitle": "Similar suggestions",
    "SingleMatchingSuggestionLabel": "1 matching suggestion",
    "MultipleMatchingSuggestionsLabel": "{0} matching suggestions",
    "SearchLabel": "Search",
    "SearchPlaceholder": "Search by title or details",
    "AllCategoriesOptionLabel": "All categories",
    "AllSubcategoriesOptionLabel": "All subcategories"
  }
});
