define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ListFieldLabel": "Suggestions list",
    "VoteListFieldLabel": "Votes list",
    "SubcategoryListFieldLabel": "Subcategory list",
    "SubcategoryListNoneOptionLabel": "Do not use subcategories",
    "CreateSuggestionsListButtonLabel": "Create or update suggestions list",
    "CreateVotesListButtonLabel": "Create or update votes list",
    "CreateSubcategoryListButtonLabel": "Create or update subcategory list",
    "CreateSuggestionsListProgressMessage": "Creating or updating the suggestions list...",
    "CreateVotesListProgressMessage": "Creating or updating the votes list...",
    "CreateSubcategoryListProgressMessage": "Creating or updating the subcategory list...",
    "SubcategoryManagementLabel": "Manage subcategories",
    "SubcategoryItemsFieldLabel": "Existing subcategories",
    "SubcategoryDropdownPlaceholder": "No subcategories found",
    "NewSubcategoryFieldLabel": "New subcategory name",
    "NewSubcategoryFieldPlaceholder": "Enter a subcategory name",
    "AddSubcategoryButtonAriaLabel": "Add subcategory",
    "RemoveSubcategoryButtonAriaLabel": "Remove selected subcategory",
    "SubcategoryNameMissingMessage": "Enter a name before adding a subcategory.",
    "SubcategoryListNotConfiguredMessage": "Select or create a subcategory list before managing entries.",
    "SubcategoryUpdateProgressMessage": "Updating subcategories...",
    "SubcategoryUpdateSuccessMessage": "Subcategories updated.",
    "SubcategoryUpdateErrorMessage": "We couldn't update the subcategory list. Please try again.",
    "SubcategoryLoadErrorMessage": "We couldn't load subcategories. Please verify the list and try again.",
    "SubcategoryAddedMessage": "Added subcategory \"{0}\".",
    "SubcategoryRemovedMessage": "Removed the selected subcategory.",
    "SubcategorySelectionMissingMessage": "Select a subcategory before removing it.",
    "CreateListSuccessMessage": "The list \"{0}\" is ready to use.",
    "CreateListAlreadyExistsMessage": "The list already existed. Missing fields were added if necessary.",
    "CreateListNameMissingMessage": "Enter a name before creating the list.",
    "CreateListErrorMessage": "We couldn't create or update the list. Please try again.",
    "CreateListPromptMessage": "Enter a name for the {0}:",
    "CreateListPromptSuggestionsLabel": "suggestions list",
    "CreateListPromptVotesLabel": "votes list",
    "CreateListPromptSubcategoryLabel": "subcategory list",
    "UseTableLayoutToggleLabel": "Suggestion layout",
    "UseTableLayoutToggleOnText": "Table",
    "UseTableLayoutToggleOffText": "Cards"
  }
});
