define([], function() {
  return {
    "PropertyPaneDescription": "Beskrivning",
    "BasicGroupName": "Gruppnamn",
    "DescriptionFieldLabel": "Beskrivningsfält",
    "HeaderTitleFieldLabel": "Rubriktitel",
    "HeaderSubtitleFieldLabel": "Rubrikens underrubrik",
    "AppLocalEnvironmentSharePoint": "Appen körs i din lokala miljö som en SharePoint-webbdel",
    "AppLocalEnvironmentTeams": "Appen körs i din lokala miljö som en Microsoft Teams-app",
    "AppLocalEnvironmentOffice": "Appen körs i din lokala miljö på office.com",
    "AppLocalEnvironmentOutlook": "Appen körs i din lokala miljö i Outlook",
    "AppSharePointEnvironment": "Appen körs på en SharePoint-sida",
    "AppTeamsTabEnvironment": "Appen körs i Microsoft Teams",
    "AppOfficeEnvironment": "Appen körs på office.com",
    "AppOutlookEnvironment": "Appen körs i Outlook",
    "UnknownEnvironment": "Appen körs i en okänd miljö",
    "ListFieldLabel": "Förslagslista",
    "VoteListFieldLabel": "Röstlista",
    "SubcategoryListFieldLabel": "Underkategorilista",
    "SubcategoryListNoneOptionLabel": "Använd inte underkategorier",
    "CreateSuggestionsListButtonLabel": "Skapa eller uppdatera förslagslistan",
    "CreateVotesListButtonLabel": "Skapa eller uppdatera röstlistan",
    "CreateSubcategoryListButtonLabel": "Skapa eller uppdatera underkategorilistan",
    "CreateSuggestionsListProgressMessage": "Skapar eller uppdaterar förslagslistan...",
    "CreateVotesListProgressMessage": "Skapar eller uppdaterar röstlistan...",
    "CreateSubcategoryListProgressMessage": "Skapar eller uppdaterar underkategorilistan...",
    "SubcategoryManagementLabel": "Hantera underkategorier",
    "SubcategoryItemsFieldLabel": "Befintliga underkategorier",
    "SubcategoryDropdownPlaceholder": "Inga underkategorier hittades",
    "NewSubcategoryFieldLabel": "Ny underkategori",
    "NewSubcategoryFieldPlaceholder": "Ange ett namn på en underkategori",
    "AddSubcategoryButtonAriaLabel": "Lägg till underkategori",
    "RemoveSubcategoryButtonAriaLabel": "Ta bort vald underkategori",
    "SubcategoryNameMissingMessage": "Ange ett namn innan du lägger till en underkategori.",
    "SubcategoryListNotConfiguredMessage": "Välj eller skapa en underkategorilista innan du hanterar poster.",
    "SubcategoryUpdateProgressMessage": "Uppdaterar underkategorier...",
    "SubcategoryUpdateSuccessMessage": "Underkategorierna har uppdaterats.",
    "SubcategoryUpdateErrorMessage": "Vi kunde inte uppdatera underkategorilistan. Försök igen.",
    "SubcategoryLoadErrorMessage": "Vi kunde inte läsa in underkategorier. Kontrollera listan och försök igen.",
    "SubcategoryAddedMessage": "Lade till underkategorin \"{0}\".",
    "SubcategoryRemovedMessage": "Tog bort den valda underkategorin.",
    "SubcategorySelectionMissingMessage": "Välj en underkategori innan du tar bort den.",
    "CreateListSuccessMessage": "Listan \"{0}\" är klar att användas.",
    "CreateListAlreadyExistsMessage": "Listan fanns redan. Saknade fält lades till vid behov.",
    "CreateListNameMissingMessage": "Ange ett namn innan du skapar listan.",
    "CreateListErrorMessage": "Vi kunde inte skapa eller uppdatera listan. Försök igen.",
    "CreateListPromptMessage": "Ange ett namn för {0}:",
    "CreateListPromptSuggestionsLabel": "förslagslistan",
    "CreateListPromptVotesLabel": "röstlistan",
    "CreateListPromptSubcategoryLabel": "underkategorilistan",
    "UseTableLayoutToggleLabel": "Förslagslayout",
    "UseTableLayoutToggleOnText": "Tabell",
    "UseTableLayoutToggleOffText": "Kort"
  }
});
