define([], function() {
  return {
    "PropertyPaneDescription": "Beskrivning",
    "BasicGroupName": "Gruppnamn",
    "DescriptionFieldLabel": "Beskrivningsfält",
    "HeaderTitleFieldLabel": "Rubriktitel",
    "HeaderSubtitleFieldLabel": "Rubrikens underrubrik",
    "AppLocalEnvironmentSharePoint": "Appen körs i din lokala miljö som en SharePoint-webbdel",
    "AppLocalEnvironmentTeams": "Appen körs i din lokala miljö som en Microsoft Teams-app",
    "AppLocalEnvironmentOffice": "Appen körs i din lokala miljö på office.com",
    "AppLocalEnvironmentOutlook": "Appen körs i din lokala miljö i Outlook",
    "AppSharePointEnvironment": "Appen körs på en SharePoint-sida",
    "AppTeamsTabEnvironment": "Appen körs i Microsoft Teams",
    "AppOfficeEnvironment": "Appen körs på office.com",
    "AppOutlookEnvironment": "Appen körs i Outlook",
    "UnknownEnvironment": "Appen körs i en okänd miljö",
    "ListFieldLabel": "Förslagslista",
    "VoteListFieldLabel": "Röstlista",
    "CategoryListFieldLabel": "Kategorilista",
    "CategoryListDefaultOptionLabel": "Använd standardkategorierna",
    "SubcategoryListFieldLabel": "Underkategorilista",
    "SubcategoryListNoneOptionLabel": "Använd inte underkategorier",
    "CreateSuggestionsListButtonLabel": "Skapa eller uppdatera förslagslistan",
    "CreateVotesListButtonLabel": "Skapa eller uppdatera röstlistan",
    "CreateCategoryListButtonLabel": "Skapa eller uppdatera kategorilistan",
    "CreateSubcategoryListButtonLabel": "Skapa eller uppdatera underkategorilistan",
    "CreateSuggestionsListProgressMessage": "Skapar eller uppdaterar förslagslistan...",
    "CreateVotesListProgressMessage": "Skapar eller uppdaterar röstlistan...",
    "CreateCategoryListProgressMessage": "Skapar eller uppdaterar kategorilistan...",
    "CreateSubcategoryListProgressMessage": "Skapar eller uppdaterar underkategorilistan...",
    "CategoryManagementLabel": "Hantera kategorier",
    "SubcategoryManagementLabel": "Hantera underkategorier",
    "CategoryItemsFieldLabel": "Befintliga kategorier",
    "SubcategoryItemsFieldLabel": "Befintliga underkategorier",
    "CategoryDropdownPlaceholder": "Inga kategorier hittades",
    "SubcategoryDropdownPlaceholder": "Inga underkategorier hittades",
    "NewCategoryFieldLabel": "Namn på ny kategori",
    "NewSubcategoryFieldLabel": "Ny underkategori",
    "NewCategoryFieldPlaceholder": "Ange ett namn på en kategori",
    "NewSubcategoryFieldPlaceholder": "Ange ett namn på en underkategori",
    "AddCategoryButtonAriaLabel": "Lägg till kategori",
    "AddSubcategoryButtonAriaLabel": "Lägg till underkategori",
    "RemoveCategoryButtonAriaLabel": "Ta bort vald kategori",
    "RemoveSubcategoryButtonAriaLabel": "Ta bort vald underkategori",
    "CategoryNameMissingMessage": "Ange ett namn innan du lägger till en kategori.",
    "SubcategoryNameMissingMessage": "Ange ett namn innan du lägger till en underkategori.",
    "CategoryListNotConfiguredMessage": "Välj eller skapa en kategorilista eller använd standardkategorierna innan du hanterar poster.",
    "SubcategoryListNotConfiguredMessage": "Välj eller skapa en underkategorilista innan du hanterar poster.",
    "CategoryUpdateProgressMessage": "Uppdaterar kategorier...",
    "SubcategoryUpdateProgressMessage": "Uppdaterar underkategorier...",
    "CategoryUpdateSuccessMessage": "Kategorierna har uppdaterats.",
    "SubcategoryUpdateSuccessMessage": "Underkategorierna har uppdaterats.",
    "CategoryUpdateErrorMessage": "Vi kunde inte uppdatera kategorilistan. Försök igen.",
    "SubcategoryUpdateErrorMessage": "Vi kunde inte uppdatera underkategorilistan. Försök igen.",
    "CategoryLoadErrorMessage": "Vi kunde inte läsa in kategorier. Kontrollera listan och försök igen.",
    "SubcategoryLoadErrorMessage": "Vi kunde inte läsa in underkategorier. Kontrollera listan och försök igen.",
    "CategoryAddedMessage": "Lade till kategorin \"{0}\".",
    "SubcategoryAddedMessage": "Lade till underkategorin \"{0}\".",
    "CategoryRemovedMessage": "Tog bort den valda kategorin.",
    "SubcategoryRemovedMessage": "Tog bort den valda underkategorin.",
    "CategorySelectionMissingMessage": "Välj en kategori innan du tar bort den.",
    "SubcategorySelectionMissingMessage": "Välj en underkategori innan du tar bort den.",
    "CreateListSuccessMessage": "Listan \"{0}\" är klar att användas.",
    "CreateListAlreadyExistsMessage": "Listan fanns redan. Saknade fält lades till vid behov.",
    "CreateListNameMissingMessage": "Ange ett namn innan du skapar listan.",
    "CreateListErrorMessage": "Vi kunde inte skapa eller uppdatera listan. Försök igen.",
    "CreateListPromptMessage": "Ange ett namn för {0}:",
    "CreateListPromptSuggestionsLabel": "förslagslistan",
    "CreateListPromptVotesLabel": "röstlistan",
    "CreateListPromptCategoryLabel": "kategorilistan",
    "CreateListPromptSubcategoryLabel": "underkategorilistan",
    "UseTableLayoutToggleLabel": "Förslagslayout",
    "UseTableLayoutToggleOnText": "Tabell",
    "UseTableLayoutToggleOffText": "Kort"
  }
});
