define([], function() {
  return {
    "PropertyPaneDescription": "Beskrivning",
    "BasicGroupName": "Gruppnamn",
    "DescriptionFieldLabel": "Beskrivningsfält",
    "HeaderTitleFieldLabel": "Rubriktitel",
    "HeaderSubtitleFieldLabel": "Rubrikens underrubrik",
    "DefaultSuggestionsHeaderTitle": "Förslagstavla",
    "DefaultSuggestionsHeaderSubtitle": "Dela idéer, rösta och fira det som levererats.",
    "DefaultStatusDefinitions": "Aktiv\nPågår\nKlar",
    "AppLocalEnvironmentSharePoint": "Appen körs i din lokala miljö som en SharePoint-webbdel",
    "AppLocalEnvironmentTeams": "Appen körs i din lokala miljö som en Microsoft Teams-app",
    "AppLocalEnvironmentOffice": "Appen körs i din lokala miljö på office.com",
    "AppLocalEnvironmentOutlook": "Appen körs i din lokala miljö i Outlook",
    "AppSharePointEnvironment": "Appen körs på en SharePoint-sida",
    "AppTeamsTabEnvironment": "Appen körs i Microsoft Teams",
    "AppOfficeEnvironment": "Appen körs på office.com",
    "AppOutlookEnvironment": "Appen körs i Outlook",
    "UnknownEnvironment": "Appen körs i en okänd miljö",
    "ListFieldLabel": "Förslagslista",
    "VoteListFieldLabel": "Röstlista",
    "TotalVotesPerUserFieldLabel": "Röster per användare",
    "TotalVotesPerUserFieldDescription": "Lämna tomt för att använda standardvärdet ({0} röster per kategori).",
    "TotalVotesPerUserFieldErrorMessage": "Ange ett positivt heltal.",
    "CommentListFieldLabel": "Kommentarslista",
    "CategoryListFieldLabel": "Kategorilista",
    "CategoryListDefaultOptionLabel": "Använd standardkategorierna",
    "SubcategoryListFieldLabel": "Underkategorilista",
    "SubcategoryListNoneOptionLabel": "Använd inte underkategorier",
    "StatusListFieldLabel": "Statuslista",
    "StatusListDefaultOptionLabel": "Använd fördefinierade statusar",
    "CreateSuggestionsListButtonLabel": "Skapa eller uppdatera förslagslistan",
    "CreateVotesListButtonLabel": "Skapa eller uppdatera röstlistan",
    "CreateCommentsListButtonLabel": "Skapa eller uppdatera kommentarslistan",
    "CreateCategoryListButtonLabel": "Skapa eller uppdatera kategorilistan",
    "CreateSubcategoryListButtonLabel": "Skapa eller uppdatera underkategorilistan",
    "CreateStatusListButtonLabel": "Skapa eller uppdatera statuslistan",
    "CreateSuggestionsListProgressMessage": "Skapar eller uppdaterar förslagslistan...",
    "CreateVotesListProgressMessage": "Skapar eller uppdaterar röstlistan...",
    "CreateCommentsListProgressMessage": "Skapar eller uppdaterar kommentarslistan...",
    "CreateCategoryListProgressMessage": "Skapar eller uppdaterar kategorilistan...",
    "CreateSubcategoryListProgressMessage": "Skapar eller uppdaterar underkategorilistan...",
    "CreateStatusListProgressMessage": "Skapar eller uppdaterar statuslistan...",
    "CategoryManagementLabel": "Hantera kategorier",
    "SubcategoryManagementLabel": "Hantera underkategorier",
    "StatusManagementLabel": "Hantera statusar",
    "CategoryItemsFieldLabel": "Befintliga kategorier",
    "SubcategoryItemsFieldLabel": "Befintliga underkategorier",
    "StatusItemsFieldLabel": "Befintliga statusar",
    "CategoryDropdownPlaceholder": "Inga kategorier hittades",
    "SubcategoryDropdownPlaceholder": "Inga underkategorier hittades",
    "StatusDropdownPlaceholder": "Inga statusar hittades",
    "NewCategoryFieldLabel": "Namn på ny kategori",
    "NewSubcategoryFieldLabel": "Ny underkategori",
    "NewStatusFieldLabel": "Nytt statusnamn",
    "NewCategoryFieldPlaceholder": "Ange ett namn på en kategori",
    "NewSubcategoryFieldPlaceholder": "Ange ett namn på en underkategori",
    "NewStatusFieldPlaceholder": "Ange ett statusnamn",
    "AddCategoryButtonAriaLabel": "Lägg till kategori",
    "AddSubcategoryButtonAriaLabel": "Lägg till underkategori",
    "AddStatusButtonAriaLabel": "Lägg till status",
    "RemoveCategoryButtonAriaLabel": "Ta bort vald kategori",
    "RemoveSubcategoryButtonAriaLabel": "Ta bort vald underkategori",
    "RemoveStatusButtonAriaLabel": "Ta bort vald status",
    "CategoryNameMissingMessage": "Ange ett namn innan du lägger till en kategori.",
    "SubcategoryNameMissingMessage": "Ange ett namn innan du lägger till en underkategori.",
    "StatusNameMissingMessage": "Ange ett namn innan du lägger till en status.",
    "CategoryListNotConfiguredMessage": "Välj eller skapa en kategorilista eller använd standardkategorierna innan du hanterar poster.",
    "SubcategoryListNotConfiguredMessage": "Välj eller skapa en underkategorilista innan du hanterar poster.",
    "StatusListNotConfiguredMessage": "Välj eller skapa en statuslista innan du hanterar poster.",
    "CategoryUpdateProgressMessage": "Uppdaterar kategorier...",
    "SubcategoryUpdateProgressMessage": "Uppdaterar underkategorier...",
    "StatusUpdateProgressMessage": "Uppdaterar statusar...",
    "CategoryUpdateSuccessMessage": "Kategorierna har uppdaterats.",
    "SubcategoryUpdateSuccessMessage": "Underkategorierna har uppdaterats.",
    "StatusUpdateSuccessMessage": "Statusar uppdaterade.",
    "CategoryUpdateErrorMessage": "Vi kunde inte uppdatera kategorilistan. Försök igen.",
    "SubcategoryUpdateErrorMessage": "Vi kunde inte uppdatera underkategorilistan. Försök igen.",
    "StatusUpdateErrorMessage": "Vi kunde inte uppdatera statuslistan. Försök igen.",
    "CategoryLoadErrorMessage": "Vi kunde inte läsa in kategorier. Kontrollera listan och försök igen.",
    "SubcategoryLoadErrorMessage": "Vi kunde inte läsa in underkategorier. Kontrollera listan och försök igen.",
    "StatusLoadErrorMessage": "Vi kunde inte läsa in statusar. Kontrollera listan och försök igen.",
    "StatusListLoadErrorMessage": "Vi kunde inte läsa in den konfigurerade statuslistan. Kontrollera inställningen eller ta bort den.",
    "CategoryAddedMessage": "Lade till kategorin \"{0}\".",
    "SubcategoryAddedMessage": "Lade till underkategorin \"{0}\".",
    "StatusAddedMessage": "Lade till statusen \"{0}\".",
    "CategoryRemovedMessage": "Tog bort den valda kategorin.",
    "SubcategoryRemovedMessage": "Tog bort den valda underkategorin.",
    "StatusRemovedMessage": "Tog bort den valda statusen.",
    "CategorySelectionMissingMessage": "Välj en kategori innan du tar bort den.",
    "SubcategorySelectionMissingMessage": "Välj en underkategori innan du tar bort den.",
    "StatusSelectionMissingMessage": "Välj en status innan du tar bort den.",
    "CreateListSuccessMessage": "Listan \"{0}\" är klar att användas.",
    "CreateListAlreadyExistsMessage": "Listan fanns redan. Saknade fält lades till vid behov.",
    "CreateListNameMissingMessage": "Ange ett namn innan du skapar listan.",
    "CreateListErrorMessage": "Vi kunde inte skapa eller uppdatera listan. Försök igen.",
    "CreateListPromptMessage": "Ange ett namn för {0}:",
    "CreateListPromptSuggestionsLabel": "förslagslistan",
    "CreateListPromptVotesLabel": "röstlistan",
    "CreateListPromptCommentsLabel": "kommentarslistan",
    "CreateListPromptCategoryLabel": "kategorilistan",
    "CreateListPromptSubcategoryLabel": "underkategorilistan",
    "CreateListPromptStatusLabel": "statuslistan",
    "StatusDefinitionsFieldLabel": "Förslagsstatusar (en per rad)",
    "CompletedStatusFieldLabel": "Status för slutfört",
    "DefaultStatusFieldLabel": "Standardstatus för nya förslag",
    "UseTableLayoutToggleLabel": "Förslagslayout",
    "UseTableLayoutToggleOnText": "Tabell",
    "UseTableLayoutToggleOffText": "Kort",
    "ShowMetadataInIdColumnLabel": "Visa kategori, underkategori och status i ID-kolumnen",
    "ShowMetadataInIdColumnOnText": "I samma kolumn",
    "ShowMetadataInIdColumnOffText": "Separata kolumner",
    "AddSuggestionSectionTitle": "Lägg till ett förslag",
    "HideSectionLabel": "Dölj avsnitt",
    "ShowSectionLabel": "Visa avsnitt",
    "PreviousButtonText": "Föregående",
    "NextButtonText": "Nästa",
    "PaginationPageLabel": "Sida {0}",
    "CreatedLabel": "Skapad",
    "LastModifiedLabel": "Senast ändrad",
    "CompletedLabel": "Slutförd",
    "VotesRemainingLabel": "Återstående röster",
    "VotesUnlimitedLabel": "Obegränsat",
    "VotesPerCategoryDefaultLabel": "Du har {0} röster per kategori",
    "CategoryLabel": "Kategori",
    "SubcategoryLabel": "Underkategori",
    "NoSubcategoriesAvailablePlaceholder": "Inga underkategorier tillgängliga",
    "SelectSubcategoryPlaceholder": "Välj en underkategori",
    "AddSuggestionTitleLabel": "Titel",
    "AddSuggestionDetailsLabel": "Detaljer",
    "SubmitSuggestionButtonText": "Skicka in förslag",
    "VoteButtonText": "Rösta",
    "RemoveVoteButtonText": "Ta bort röst",
    "VotesClosedText": "Röstning stängd",
    "AdvanceSuggestionStatusButtonText": "Flytta status",
    "RemoveSuggestionButtonLabel": "Ta bort förslag",
    "CommentsLabel": "Kommentarer",
    "AddCommentButtonText": "Lägg till kommentar",
    "HideCommentInputButtonText": "Dölj kommentarsfält",
    "CommentInputLabel": "Kommentar",
    "CommentInputPlaceholder": "Skriv din kommentar (HTML stöds)",
    "RichTextEditorBoldButtonLabel": "Fetstil",
    "RichTextEditorItalicButtonLabel": "Kursiv",
    "RichTextEditorUnderlineButtonLabel": "Understruken",
    "RichTextEditorBulletListButtonLabel": "Punktlista",
    "RichTextEditorPlaceholder": "Börja skriva...",
    "SubmitCommentButtonText": "Publicera kommentar",
    "DeleteCommentButtonLabel": "Ta bort kommentar",
    "VoteSingularLabel": "röst",
    "VotesLabel": "Röster",
    "LoadingCommentsLabel": "Läser in kommentarer...",
    "LoadingSuggestionsLabel": "Läser in förslag...",
    "SuggestionStatusUpdatedMessage": "Förslagets status har uppdaterats.",
    "SimilarSuggestionsTitle": "Liknande förslag",
    "SingleMatchingSuggestionLabel": "1 matchande förslag",
    "MultipleMatchingSuggestionsLabel": "{0} matchande förslag",
    "SimilarSuggestionsQueryPrefix": "Visar resultat för",
    "SimilarSuggestionsQuerySeparator": "och",
    "SimilarSuggestionsQueryTitleLabel": "titel",
    "SimilarSuggestionsQueryDescriptionLabel": "beskrivning",
    "SimilarSuggestionsLoadingLabel": "Söker...",
    "NoSimilarSuggestionsLabel": "Inga liknande förslag hittades.",
    "NoCommentsLabel": "Inga kommentarer än.",
    "NoSuggestionsLabel": "Det finns inga förslag i det här avsnittet än.",
    "NoVotedSuggestionsLabel": "Du har inte röstat på några förslag ännu.",
    "TopSuggestionsLoadErrorMessage": "Vi kunde inte läsa in de mest röstade förslagen. Försök igen.",
    "SuggestionTableSuggestionColumnLabel": "Förslag",
    "SuggestionTableActionsColumnLabel": "Åtgärder",
    "SuggestionTableEntryColumnLabel": "Post",
    "SuggestionTableDetailsColumnLabel": "Detaljer",
    "StatusLabel": "Status",
    "EntryAriaLabel": "Post {0}",
    "ActiveSuggestionsSectionTitle": "Aktiva förslag",
    "CompletedSuggestionsSectionTitle": "Slutförda förslag",
    "ActiveSuggestionsTabLabel": "Aktiva förslag",
    "CompletedSuggestionsTabLabel": "Avslutade förslag",
    "AdminTopSuggestionsTabLabel": "Toppförslag",
    "MyVotesTabLabel": "Mina röster",
    "DefaultCategoryChangeRequest": "Ändringsförslag",
    "DefaultCategoryWebinar": "Webbinarium",
    "DefaultCategoryArticle": "Artikel",
    "SearchLabel": "Sök",
    "SearchPlaceholder": "Sök efter titel eller detaljer",
    "ClearFiltersButtonText": "Rensa filter",
    "AllCategoriesOptionLabel": "Alla kategorier",
    "AllSubcategoriesOptionLabel": "Alla underkategorier",
    "AllStatusesOptionLabel": "Alla statusar",
    "NoVotesRemainingForCategoryMessage": "Du har använt alla dina röster för den här kategorin. Ta bort en röst för att fortsätta."
  }
});
